### ISSUE TITLE
Error inputing a single sample

### ISSUE THREAD

**Issue by james-e-barrett** [sjczheng/EpiDISH#11]
Inputting a beta matrix with one column generates an error:
```
out.l <- epidish(beta.m = DummyBeta.m[,1,drop=FALSE], ref.m = centEpiFibIC.m, method = "RPC") 
Error in matrix(nrow = ncol(data2.m), ncol = ncol(ref2.m)) : 
  non-numeric matrix extent
```
Possible fix on line 5 of DoRPC?
`data2.m <- beta.m[map.idx[rep.idx], ,drop=FALSE]`

**Comment by sjczheng** [comment]
Hi James,

Thanks so much.
We have now fixed the issue.

Best,
Shijie
