### ISSUE TITLE
Missing cell references

### ISSUE THREAD

**Issue by iskandari** [sjczheng/EpiDISH#12]
Thanks for creating this useful [online tool](https://www.biosino.org/EpiDISH/)  alongside this package.  It seems that in the dropdown menu where one selects a reference, there are 17 individual types of references, some of which (i.e. brain tissue) are not included in the R package data. It seems that selecting brain reference in the online tool also fails even when the data is properly prepared (see screenshot below) .  Would it be possible to include or add the remainder of the cell references matrices available in the online tool here in the repo as well? Thank you!

<img width="1125" alt="Screenshot 2023-01-19 at 3 36 00 AM" src="https://user-images.githubusercontent.com/8308461/213342348-6912cde5-2d82-4ff8-bbd9-35be3ee0d4f8.png">

**Comment by sjczheng** [comment]
Hi,

Thanks for your interest in our tools.
We are now keeping the references separately in two packages.
The 17 reference you are interested in can be found in the Episcore package at https://github.com/aet21/EpiSCORE or https://www.biosino.org/episcore/

If you use these 17 references, please cite the episcore resource paper "Zhu, T., Liu, J., Beck, S., Pan, S., Capper, D., Lechner, M., Thirlwell, C., Breeze, C. E., & Teschendorff, A. E. (2022). A pan-tissue DNA methylation atlas enables in silico decomposition of human tissue methylomes at cell-type resolution. Nature methods, 19(3), 296–306. https://doi.org/10.1038/s41592-022-01412-7"

Thanks.
