### ISSUE TITLE
Interpretation of CellDMC estimates for individual cell-types

### ISSUE THREAD

**Issue by ofsolomon** [sjczheng/EpiDISH#14]
Hello, 

I am using cellDMC to estimate differential methylation in the cell-types I estimated from HEpiDISH. I have a binary phenotype. For a large number of significant CpGs, I am seeing estimates equal to -1 or 1. Since this is a coefficient estimated from regression of methylation beta values, my understanding is that this means there is a 100% difference in methylation in this cell-type between my two phenotypes on interest (ie. all of 1 phenotype are _completely_ _unmethylated_ at this site and all of the other phenotype are _completely_ _methylated_ at this site) 

If I am properly interpreting these results, does it seem reasonable to see results like this for 100s of CpGs? I want to be sure I am using this tool properly as I am not used to seeing effect sizes of -1 and 1 in differential methylation analysis with beta values. 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/27368230/236579043-6f069b33-28a9-49dc-9c19-6e6e18594653.png">

Thank you, 
Olivia

**Comment by sjczheng** [comment]
Hi,

Based on your description, it sounds like you are running the CellDMC
function in EpiDISH correctly. A coefficient estimate of -1 or 1 for a CpG
site in a particular cell-type indicates a complete difference in
methylation levels between the two phenotypes you are comparing.
Note that to estimate the coefficient of each cell type, we need to include
2* the number of cell type in the statistical model.
When there are multiple variables included in the model, the variability of
the model increases, which can lead to more extreme coefficient estimates.
Mathematically, these extreme estimates make sense.
However, when interpreting the results, it is also important to consider
the biological relevance of the CpG sites that are showing significant
differences, as well as any potential confounding factors that may be
affecting the results.
Additionally, it is worth considering the sample size and the fractions of
B cells in your samples.

Best,
Shijie
