### ISSUE TITLE
Version 2.15 or later

### ISSUE THREAD

**Issue by CPRyan** [sjczheng/EpiDISH#17]
I'm attempting to use EpiDISH to estimate 12 cell counts. However, when I download from Bioconductor the latest version is 2.14.1. This doesn't have the reference panel for the 12 cell counts. 

Do you know when the 2.15 version (or later) will be released on Bioconductor, or can you suggest another way to download 2.15 or later?

**Comment by sjczheng** [comment]
The latest release version of Bioconductor is 3.17. 
And the EpiDISH version in the current Bioc is 2.16.0.
https://www.bioconductor.org/packages/release/bioc/html/EpiDISH.html

You should use the latest Bioconductor package.

**Comment by sjczheng** [comment]
If you cannot upgrade your BioManager package.
You should upgrade your R.
