### ISSUE TITLE
reference data not found 

### ISSUE THREAD

**Issue by Candacerl** [sjczheng/EpiDISH#2]
Hello, 

I have successfully loaded the EpiDISH library with the following code:

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("EpiDISH", version = "3.8")
library(EpiDISH) 

However, when I try to load data(centEpiFibIC.m) it errors that it cannot be found. 

Please advise, thank you!

**Comment by Raphouu** [comment]
Hello !
I had the same problem and I have downloaded the data in my documents directory and loaded it in R with the following code: 
load(file = "C:/Users/Username/Documents/centEpiFibIC.m.rda")

Hope this will help, 

Raphaële

**Comment by Raphouu** [comment]
Alternatively you can install the EpiDISH R package from Github with the following code:
library(devtools)
install_github("sjczheng/EpiDISH")

**Comment by Candacerl** [comment]
> Hello !
> I had the same problem and I have downloaded the data in my documents directory and loaded it in R with the following code:
> load(file = "C:/Users/Username/Documents/centEpiFibIC.m.rda")
> 
> Hope this will help,
> 
> Raphaële

Thank you! Where did you download it from?

**Comment by sjczheng** [comment]
Hi. The reference EpiFibIC is included in the new version of EpiDISH package, which is now only on the development branch of Bioconductor now. 
BiocManager::install("EpiDISH", version = "3.8") will install the old version, which is on release branch of Bioconductor. 
The rollover should happen in next April.
To install the new version of EpiDISH, you can use devtools::install_github("sjczheng/EpiDISH")
Or you can install from BioC development branch BiocManager::install("EpiDISH", version = "devel")
