### ISSUE TITLE
How many samples of each group are needed to use EpiDISH?

### ISSUE THREAD

**Issue by CTLife** [sjczheng/EpiDISH#3]
Can I use EpiDISH for  a small sample size ?   Such as 18 samples of each group.

**Comment by sjczheng** [comment]
Hi. Sorry for the delayed response. Which function are you asking? If you refer to the fraction estimation function, only one sample is enough to run the function, as the estimation for each sample is independent. If you are asking for CellDMC, the minimum sample size depends on the effect size.
