### ISSUE TITLE
Hepidish

### ISSUE THREAD

**Issue by Irina0905** [sjczheng/EpiDISH#4]
hello, I am analysing my DNAm data for lung tissue, I can not install the new  version of epidish, so I use twice epidish for my data with the differerent ref.(centEpiFibIC.m, centBloodSub.m), then use the IC proportion * subtype proportion. Is that correct?  
I also want to know I have to establish new ref. if I want to the proportion of macrophage ?
Thanks

**Comment by sjczheng** [comment]
Hi. Sorry for the delayed response. The way you applied hepidish was correct. And macrophages are differentiated from monocytes. If you want to build a reference if you need to get DNAm profiles on the sorted cell-type.
