### ISSUE TITLE
Estimations with NA

### ISSUE THREAD

**Issue by emarti88** [sjczheng/EpiDISH#5]
Hello,

I have been using EpiDISH to estimate neuronal proportions in DNA methylation data from bulk tissue. I have been using around 20k sites of highly discriminatory CpGs that we had previously identified.  However, recently after using the RPC method, the epidish estimates are turning out NA for some of the queried samples. I checked and made sure there were no NAs in the methylation query set but the issue persisted. 

Do you have any idea why this might be the case?

Thank you 

Eduardo

**Comment by sjczheng** [comment]
Hi Eduardo,

I think you used too many discriminatory CpGs.
Try to reduce the number of signature CpGs.
