### ISSUE TITLE
Does EpiDISH works for WGBS data?

### ISSUE THREAD

**Issue by Niinleslie** [sjczheng/EpiDISH#6]
Hi,
Can I apply EpiDISH to esitmate immune cell fractions of WGBS data from liver tumor tissues? 
If so, how should I prepare the input and ref data? (I can only find the example for beta value matrix).

Thanks!

**Comment by sjczheng** [comment]
EpiDISH can be used with WGBS data.
You need to make a reference matrix with row names as the same row names of the data matrix.
For WGBS, you can do chr.position as row names. Or you can make your own style.
The values of this reference matrix can be computed using purified WGBS or array data.
If you use array data, just remember to make sure that the genome version you are using is consistent with the array annotation when you do position liftover.

**Comment by KristenKrolick** [comment]
@sjczheng 

Hello, thank you so much for making this tool!
I am making my own reference consisting of different WGBS blood cell types and the reference data I am able to download from GEO happens to have the methylation value conventions of 1 to 1000 (they said they did meth calling with wgbstools), while my dataset has the methylation value convention as used by bismark of 0 to 1. Is this going to be a problem, or will the software somehow correct for this anyways?

Thank you!

**Comment by sjczheng** [comment]
Hi,
You need the methylated counts and unmethylated counts to calculate beta values.
The software won't correct this.

**Comment by KristenKrolick** [comment]
@sjczheng 
The reference datasets do not have methylated and unmethylated counts, they are already beta values then? 

Furthermore, I am loading my data from bismark.cov files into R using methrix to make the input matrix into Epidish. I believe methrix must be making the 'beta' values or ratio of methylation calls for me, because my input are only methylation values 0-1. Do you know if this would be fine?

Thank you for your input!
Kristen

**Comment by sunyu1010** [comment]
@sjczheng 
Hi, thank you so much for your answer! So if I want to apply EpiDISH to WGBS data, I should calculate the methylation proportion by dividing methylated counts by all counts. In other words, the methylation proportion is equivalent to beta value of arrays.
Is that true? I've just started to learn WGBS, this may be an elementary question, sorry to bother you!
