### ISSUE TITLE
Cannot Run Hepidish with beta.m set to LiuDataSub.m

### ISSUE THREAD

**Issue by ryanalomair** [sjczheng/EpiDISH#9]
Hi,
So I am trying to run Hepidish and keep running into an error. 
I am unable to run the the Hepidish using the following parameters:
beta.m = LiuDataSub.m, ref1.m = centEpiFibIC.m, ref2.m = centBloodSub.m, h.CT.idx = 3, method = 'RPC'

And I receive the following error:

Error in rlm.default(x, y, weights, method = method, wt.method = wt.method, : 'x' is singular: singular fits are not implemented in 'rlm'

1. hepidish(beta.m = LiuDataSub.m, ref1.m = centEpiFibIC.m, ref2.m = centBloodSub.m, 
 .     h.CT.idx = 3, method = "RPC")
2. DoRPC(beta.m, ref1.m, maxit)
3. rlm(data2.m[, s] ~ ref2.m, maxit = maxit)
4. rlm.formula(data2.m[, s] ~ ref2.m, maxit = maxit)
5. rlm.default(x, y, weights, method = method, wt.method = wt.method, 
.     ...)
6. stop("'x' is singular: singular fits are not implemented in 'rlm'")

I am running this on Jupyter Notebook, using R 4.1.0.

Regards,

Ryan Alomair

**Comment by sjczheng** [comment]
Hi,

You couldn't run HEpiDISH with general epithelial reference and immune cell reference on the blood cell dataset.
The LiuDataSub.m is a subset of the Liu blood cell dataset, which includes no epithelial cell or fibroblast in the samples.
In such a case, the DNAm values of some epithelial or fibroblast signature CpGs are the same across all samples.
So the subsetted data matrix will be a singular matrix, which makes the rlm fitting fail.

Best,
Shijie
